spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_selection
    username: root
    password: Sggfge44!
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate Properties
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  show-sql: true

